### ISSUE TITLE
Make Add and Remove return boolean values

### ISSUE THREAD

**Issue by samytto** [lemire/RoaringBitmap#27]
Hi,

When dealing with Roaring bitmaps in an application, I have found that it could be helpful if one is able to know, after inserting/deleting an integer to/from a Roaring bitmap using the add/remove method, if that integer was existing before in the bitmap or no. Same kind of thing done by Java collections add and remove methods. 

If one has to maintain the cardinality of integers stored in a set of Roaring bitmaps, he needs to know if an inserted/removed integer was exsiting before in the bitmap, in order to increment/decrement the global cardinality. Such a job could be realized by calling the contains method before inserting or removing an integer. However, this will make two accesses to containers. However, if the add/remove method is able to return a true or false indicating if the inserted/removed integer was or not in the bitmap, one would be able to avoid a call to contains in such situations and preserve a supplementary access to containers.

Greetings!

**Comment by lemire** [comment]
Thanks for raising the issue. This seems sensible.

The next step would be to prototype an implementation and estimate the performance penalty we can expect (preferably using the JMH framework).

Possibly, we could start first with an intermediate API extension that has add and remove methods, maybe named checkedAdd and checkedRemove... and see if they are slower. This has the benefit of not breaking or slowing down any of the existing code, while meeting your needs.

The implementation could be identical to the current add and remove implementation, with an added check to see if the cardinality of the container has changed. Since existing container can return the cardinality in constant time this should be reasonably fast. However, getting the cardinality of a container involves polymorphism, and so, possibly, some branching. It is possible that this branching could introduce latency.

Still, this could be good enough. If the methods are distinct from add and remove (e.g., checkedAdd and checkedRemove), then nobody would care if they are slightly slower.

There are more intrusive changes that one could make, of course.

Samy? Do you want to have a go at writing a prototype, using the non-intrusive approach I suggest, with a JMH performance test, and submit a PR?

**Comment by samytto** [comment]
Ok. I also think that checking the size of the containers before and after insertion/deletion is the more effective way to do that. I'm going to try this solution.

**Comment by samytto** [comment]
Thanks!

**Comment by lemire** [comment]
Issue recently resolved.
