### ISSUE TITLE
RoaringBitmap serialize and deserialize

### ISSUE THREAD

**Issue by huiwq1990** [lemire/RoaringBitmap#38]
I plan to serialize RoaringBitmap to mysql or Redis, but I can not deserialize the result. But I got I failed to find the right cookie. Anyone can help, thanks.

``` java

import java.io.DataOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.ByteBuffer;

import org.roaringbitmap.buffer.ImmutableRoaringBitmap;
import org.roaringbitmap.buffer.MutableRoaringBitmap;

public class RedisTest {

	public static void main(String[] args) throws IOException {
		MutableRoaringBitmap mrb = MutableRoaringBitmap.bitmapOf(1, 2, 3, 1000);
		System.out.println("starting with  bitmap " + mrb);
		ByteBuffer outbb = ByteBuffer.allocate(mrb.serializedSizeInBytes());
		mrb.serialize(new DataOutputStream(new OutputStream() {
			ByteBuffer mBB;

			OutputStream init(ByteBuffer mbb) {
				mBB = mbb;
				return this;
			}

			public void close() {
			}

			public void flush() {
			}

			public void write(int b) {
				mBB.put((byte) b);
			}

			public void write(byte[] b) {
				mBB.put(b);
			}

			public void write(byte[] b, int off, int l) {
				mBB.put(b, off, l);
			}
		}.init(outbb)));

		outbb.flip();


		// convert bytebuffer to byte[] and save byte[] to redis
		byte[] bytes = new byte[outbb.capacity()];		
		outbb.get(bytes,0,bytes.length);
		System.out.println("byte:"+bytes);

		//str value is from variable bytes. simulate get bitmap deserialize from redis. The result '[B@5df86e79' changes every run.
		String str ="[B@5df86e79";
		ByteBuffer bb = ByteBuffer.wrap( str.getBytes("utf-8") );
		
	
		// wrong occur
		ImmutableRoaringBitmap rev = new ImmutableRoaringBitmap(bb);
		System.out.println("read bitmap " + rev);
		
	}
}


```

**Comment by samytto** [comment]
Hi huiwq1990,

The runtime exception : "I failed to find the right cookie" occurs because you are trying to create an ImmutableRoaringBitmap using a serialized string, however ImmutableRoaringBitmap is conceived to receive a RoaringBitmap's serialized fromat when instantiated. 

Please check this code which correctly executes for example : 

import java.io.DataOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.ByteBuffer;

import org.roaringbitmap.buffer.ImmutableRoaringBitmap;
import org.roaringbitmap.buffer.MutableRoaringBitmap;

public class BufferRoaring {

    public static void main(String[] args) throws IOException {
        MutableRoaringBitmap mrb = MutableRoaringBitmap.bitmapOf(1, 2, 3, 1000);
        System.out.println("starting with  bitmap " + mrb);
        ByteBuffer outbb = ByteBuffer.allocate(mrb.serializedSizeInBytes());
        mrb.serialize(new DataOutputStream(new OutputStream() {
            ByteBuffer mBB;

            OutputStream init(ByteBuffer mbb) {
                mBB = mbb;
                return this;
            }

            public void close() {
            }

            public void flush() {
            }

            public void write(int b) {
                mBB.put((byte) b);
            }

            public void write(byte[] b) {
                mBB.put(b);
            }

            public void write(byte[] b, int off, int l) {
                mBB.put(b, off, l);
            }
        }.init(outbb)));

        outbb.flip();


        // convert bytebuffer to byte[] and save byte[] to redis
        byte[] bytes = new byte[outbb.capacity()];      
        //outbb.get(bytes,0,bytes.length);
        System.out.println("byte:"+bytes);

        //str value is from variable bytes. simulate get bitmap deserialize from redis. The result '[B@5df86e79' changes every run.
        String str ="12346[B@5df86e79";
        ByteBuffer bb = ByteBuffer.wrap(str.getBytes("utf-8") );


        // wrong occur
        ImmutableRoaringBitmap rev = new ImmutableRoaringBitmap(outbb);
        System.out.println("read bitmap " + rev);

    }
}

Can you please give more details about why do you want to create an ImmutableRoaringBitmap with this string value "[B@5df86e79" ?

**Comment by lemire** [comment]
@huiwq1990 

Firstly, I should point out that it may or may not make sense to store binary data, such as serialized bitmaps, in MySQL or Redis. It is probably better to store this data on disk, in some file, and then to store in Redis or MySQL the *location* of the bitmap. This is not specific to RoaringBitmap... Tools like Redis or MySQL are simply not optimized for the storage of binary data.

As for your specific problem, it is important to store the byte[] to a String in such a way that you can later recover exactly the byte[] array. It is unclear how you did it in your example.

Thankfully, it is not difficult to encode a byte array to a String so that it can be later recovered. A standard way is to use Base 64 : https://en.wikipedia.org/wiki/Base64

Java 8 includes Base 64, conveniently enough, so the following example code requires no particular library :

```java
/**
* This example shows how to serialize a Roaring bitmap to a String (Java 8)
*/
import org.roaringbitmap.buffer.*;
import java.io.*;
import java.nio.*;
import java.util.*;

public class SerializeToStringExample {
    
    
    
    
    // This example uses the Base64 class introduced in Java 8. Any byte[] to String encoder would do
    public static void main(String[] args) throws IOException{
        MutableRoaringBitmap mrb = MutableRoaringBitmap.bitmapOf(1,2,3,1000); 
        System.out.println("starting with  bitmap "+ mrb);
        ByteBuffer outbb = ByteBuffer.allocate(mrb.serializedSizeInBytes());
        mrb.serialize(new DataOutputStream(new OutputStream(){
            ByteBuffer mBB;
            OutputStream init(ByteBuffer mbb) {mBB=mbb; return this;}
            public void close() {}
            public void flush() {}
            public void write(int b) {
                mBB.put((byte) b);}
            public void write(byte[] b) {mBB.put(b);}            
            public void write(byte[] b, int off, int l) {mBB.put(b,off,l);}
        }.init(outbb)));
        //
        outbb.flip();
        String serializedstring = Base64.getEncoder().encodeToString(outbb.array());
        ByteBuffer newbb = ByteBuffer.wrap(Base64.getDecoder().decode(serializedstring));
        ImmutableRoaringBitmap irb = new ImmutableRoaringBitmap(newbb);
        System.out.println("read bitmap "+ irb);        
    }
}
```


Of course, this is convoluted code that it is unlikely to give you good performance. Please consider the architecture of your application carefully.


I will close this issue. Reopen if you disagree.

**Comment by huiwq1990** [comment]
lemire, Thank you very much.
I want to implement a not repeated recommendation system, you could think as recommend books. My system will generate recommend books according to user's information, if the book has every recommended, it will not recommend to that user again. 
The problem could simplify to calculate set difference(user recommended book set A and system generate recommend book set B). I plan to save A (convert to bitmap result) in Redis or mysql, as A changes often, save the bitmap in disk is a good choice? Could you give me some advices? Thanks.

**Comment by maxdemarzi** [comment]
Hey @huiwq1990 I blogged about a similar use case (using recommendations) with RoaringBitmap on http://maxdemarzi.com/2015/03/17/one-direction-relationships-in-neo4j/ maybe that'll help you out.
