### ISSUE TITLE
Possible Endianess Mismatch in Mutable / Immutable Roaring Array Serialisation?

### ISSUE THREAD

**Issue by pwebbitrs** [lemire/RoaringBitmap#47]
We are saving down mutable roaring bitmaps using memory mapped files which we later read using Immutable Roaring bitmaps. 

However, after version ``` 0.4.9 ``` we have noticed that we get  the "I failed to find the one of the right cookies" when previously we've been fine.

Note that when we serialise down a mutable bitmap the cookie token/sentinal is byte reversed (from https://github.com/lemire/RoaringBitmap/blob/master/src/main/java/org/roaringbitmap/buffer/MutableRoaringArray.java):

```
public void serialize(DataOutput out) throws IOException {
        int startOffset=0;
        boolean hasrun = hasRunCompression();
        if (hasrun) {
            out.writeInt(Integer.reverseBytes(SERIAL_COOKIE | ((this.size-1) << 16)));

...
        } else {
            out.writeInt(Integer.reverseBytes(12346));
            out.writeInt(Integer.reverseBytes(this.size));
            var6 = 8 + this.size * 4 + this.size * 4;
        }

```

And deserialising a *Mutable* bitmap also assumes a reversal:

```
public void deserialize(DataInput in) throws IOException {
        this.clear();
        // little endian
        final int cookie = Integer.reverseBytes(in.readInt());
        if ((cookie & 0xFFFF) != SERIAL_COOKIE && cookie != SERIAL_COOKIE_NO_RUNCONTAINER)
            throw new IOException("I failed to find the one of the right cookies.");
```

However when we then build up an Immutable Bitmap passing in the memory mapped buffer serialised this way we get the error. Noting the code in https://github.com/lemire/RoaringBitmap/blob/master/src/main/java/org/roaringbitmap/buffer/ImmutableRoaringArray.java , we see it does not reverse the bytes:

```
    protected ImmutableRoaringArray(ByteBuffer bbf) {
        buffer = bbf.slice();
        buffer.order(ByteOrder.LITTLE_ENDIAN);
        final int cookie = buffer.getInt(0);
        if ((cookie & 0xFFFF) != SERIAL_COOKIE && cookie != SERIAL_COOKIE_NO_RUNCONTAINER)
            throw new RuntimeException("I failed to find one of the right cookies. "+ cookie);
```

It is here we are seeing the bad cookie (value 976224256).

I think the issue is probably in the last block of code where instead of an explicit byte reversal it does:

```
buffer.order(ByteOrder.LITTLE_ENDIAN);
final int cookie = buffer.getInt(0);
```
Which is inconsistent with the other explicit reversal ops,  which is probably fine if we assume we are writing to BIG endian buffers (perhaps?) but since we are *Always* using LE buffers (in our case), It may be that we are seeing the following occur:

* Write 123457 ( explicitly reversed) to a LE buffer in mutable serialise (effectively the cookie would be BE now right?)  
* Later on using the same LE Buffer , Switch it to LE (redundant since we are already LE) ```buffer.order(ByteOrder.LITTLE_ENDIAN);``  then read back non-reversed bytes.
* Compare the reversed cookie with our expected one

Does that make sense? 

What assumptions (if any) does Roaring make about endianess of the underlying Byte Buffer?  We may have hit an edge case - but for us we want to run cross platform, and where possible be able to utilise native byte order. 

Is this a bug or is this intentional?    If the later case, then how should we be using it to prevent this issue?    As far as I can tell our usage is pretty standard. We've been using roaring for quite a while and this seemed to just suddenly occur around the 0.5 releases (I initially thought it was something we were doing wrong but now I'm not so sure). 

If you are having issues replicating we'll put a little java repro together for you.

Thanks and apologies for the essay :)

**Comment by lemire** [comment]
So we are clear, do the following examples works for  you?

https://github.com/lemire/RoaringBitmap/blob/master/examples/ImmutableRoaringBitmapExample.java

https://github.com/lemire/RoaringBitmap/blob/master/examples/SerializeToByteBufferExample.java

Do our unit tests work? (They test serialization + mapping.)

Here is what I think is happening: recently, we greatly accelerated serialization. In the past, we would first serialize integers or longs to a byte array, being careful to flip the byte order from Java's big endian to little endian. And then we would write the byte array. That offered explicit byte order, but it was painfully slow. We found it better to flip the bytes with functions such as Integer.reverseBytes and write ints and longs. I don't recall the exact numbers, but it must have doubled our serialization/deserialization speed. Now, here is where I think things may go bad for you. You might be providing a data output stream that *flips* the byte order, effectively back to Java's original big endian. That would be the case if you were to write your objects to a ByteBuffer that has had its order switched (to little endian from Java's default big endian).

Assuming you are serializing to a ByteBuffer, if I am correct, then you can fix the problem by just leaving the ByteBuffer with Java's default byte order (big endian) during serialization. Or, be explicit and force it into a big endian mode.

>If you are having issues replicating we'll put a little java repro together for you.

It would help a lot if you had a unit test, or some kind of code sample.

Just so we are clear, the Roaring format should be serialized in little endian mode (the native format for x64 PCs).


> Note that when we serialise down a mutable bitmap the cookie token/sentinal is byte reversed 

Yes, it is reversed because Java is big endian. If you do not reverse and write a Java int or long, it is going to get written as big endian.

Of course, elsewhere, your data stream could be reflipping the bytes. 

> I think the issue is probably in the last block of code where instead of an explicit byte reversal it does (...) Which is inconsistent with the other explicit reversal ops

Java is explicitly a big endian language. When we reverse byte order during serialization, this writes in little endian. When mapping the serialized data, we specify "little endian".

> What assumptions (if any) does Roaring make about endianess of the underlying Byte Buffer? 

We make no assumption, we set it explicitly, as you point out:

         buffer.order(ByteOrder.LITTLE_ENDIAN);

We do assume that the data was serialized as little endian, but that's what the code does as it reverses Java's big endian integers before writing them out.

> For us we want to run cross platform, and where possible be able to utilise native byte order.

We want the serialized format to be independent from the native byte order, for portability. So we always serialize to little endian encoding.

> since we are Always using LE buffers (in our case), It may be that we are seeing the following occur:

Roaring does not write to buffers. It writes to a DataOuput interface.

Maybe one way to avoid problems in the future would be for us to provide an API call that serializes to byte buffers.

> Is this a bug or is this intentional? If the later case, then how should we be using it to prevent this issue? As far as I can tell our usage is pretty standard. We've been using roaring for quite a while and this seemed to just suddenly occur around the 0.5 releases (I initially thought it was something we were doing wrong but now I'm not so sure).

Sorry for these problems, and I am eager to help.

**Comment by lemire** [comment]
Note that if you serialize to a ByteBuffer the way I recommend you probably won't have any problem with byte order:
https://github.com/lemire/RoaringBitmap/blob/master/examples/SerializeToByteBufferExample.java#L18-L28

**Comment by lemire** [comment]
I have improved the API comments to clarify this issue, see this commit: 

https://github.com/lemire/RoaringBitmap/commit/a074ff0661fc3099801b520f528b388102b4d943

**Comment by pwebbitrs** [comment]
Thanks for your comments @lemire 

Yes we are using already Little Endian switched buffers and I think this is reflected in our DOS implementation which technically is incorrect as DOS makes a (not enforced, and easily forgotten) expectation that it is dealing in Big Endian (as you said above).  We've just got away with it up to now!  So It's likely on our side (apologies).   We try to use Native Endian (almost always LE) where possible. Having the option to use a Byte Buffer directly for serialisation would be nice here .

**Comment by lemire** [comment]
@pwebbitrs 

Ok. So you ought to be able to just use the code I have posted, to get around the issue.

I am going to close this one off for now. Note that I have added better documentation, so this should help future users.

However, if you have a bit of time, going through the code and writing methods to serialize directly to a ByteBuffer would not be hard to hack. That would be a great contribution to the project and it may speed up this particular form of serialization. (The hard part is to make sure that the code does what it is supposed to do.)

**Comment by pwebbitrs** [comment]
Yeah I would love to contribute.  I have things working fine now using a separate DataOutput implementation that is behaving itself.

**Comment by lemire** [comment]
@pwebbitrs  My intuition is that we could maybe double in-memory serialization speed by going directly to a ByteBuffer, skipping the ByteBuffer.

**Comment by pwebbitrs** [comment]
Yes.  I think the main thing to consider is how to introduce the use of Byte Buffers in the serialisation without replicating everything from the current DataOutput based serialisation.  But perhaps an initial take on this might have to focus on speed over reducing code replication. At least it might give an indication of potential gains.

**Comment by lemire** [comment]
The serialization code is not especially complicated... and it should be easy to test, since you can just compare the outputs to see if they are byte-by-byte identical.

**Comment by pwebbitrs** [comment]
For sure it isn't complicated at all. I will get onto this shortly.
