### ISSUE TITLE
RoaringBitmap.andNot results in a NegativeArraySizeException

### ISSUE THREAD

**Issue by maciej** [lemire/RoaringBitmap#55]
For some 2 bitmaps the `RoaringBitmap.andNot` operation results in the following error:

```
java.lang.NegativeArraySizeException
	at org.roaringbitmap.ArrayContainer.<init>(ArrayContainer.java:40)
	at org.roaringbitmap.BitmapContainer.toArrayContainer(BitmapContainer.java:772)
	at org.roaringbitmap.BitmapContainer.andNot(BitmapContainer.java:224)
	at org.roaringbitmap.Container.andNot(Container.java:142)
	at org.roaringbitmap.RoaringBitmap.andNot(RoaringBitmap.java:105)
```

Bitmaps were created adding elements by one by one. `trim()` and `runOptimize()` were not run. Running those operations fixes the problem. However, I think it's still a bug.

If the error cannot be reproduced purely from on the stack trace, I will try to extract the piece of data that caused the issue. Unfortunately, I cannot provide the whole bitmaps.

Running Oracle's jdk1.8.0_60
RoaringBitmaps 0.5.9
OSX 10.11.1

**Comment by lemire** [comment]
@maciej 

Thanks for the report. For such a problem, it is unlikely that the specific JDK or operating system you are using matter.

We have quite a bit of unit tests for andNot, so it looks like code path is tested. Looking at the code, I cannot guess how we might end up with a negative cardinality. I am also not sure how calling ```trim``` and/or ```runOptimize``` could fix such a problem.

I'll assume that you have checked for concurrency/parallelism issues.

A test case is definitively best, and might be needed here.

If you really can't do that, then you might be able to  rebuild RoaringBitmap with some printouts so we can tell a bit more about what is going on... 

In BitmapContainer, replace the andNot method by this one...

```
    @Override
    public Container andNot(final ArrayContainer value2) {
        final BitmapContainer answer = clone();
        System.out.println("answer's card is "+ answer.getCardinality());
        int myoc = answer.cardinality;
        answer.computeCardinality();
        if(myoc != answer.cardinality) throw new RuntimeException("bitmap container in bad state, actual card is "+answer.cardinality);
        int c = value2.cardinality;
        System.out.println("value2's card is "+ c);
        for (int k = 0; k < c; ++k) {
            short v = value2.content[k];
            final int i = Util.toIntUnsigned(v) >>> 6;
            long w = answer.bitmap[i];
            long aft = w & (~(1l << v));
            answer.bitmap[i] = aft;
            answer.cardinality -= (w ^ aft) >>> v;
            int myc = answer.cardinality;
            answer.computeCardinality();
            if(myc != answer.cardinality) throw new RuntimeException("logical bug?");
        }
        System.out.println("answer's final card is "+ answer.getCardinality());
        answer.computeCardinality();
        System.out.println("answer's corrected final card is "+ answer.getCardinality());
        if (answer.cardinality <= ArrayContainer.DEFAULT_MAX_SIZE)
            return answer.toArrayContainer();
        return answer;
    }
```

If we get an exception due to a logical bug, then something is wrong with our logic...  That seems unlikely given the testing that this could received, but it is always possible that we missed something.

As I wrote, I will definitively need more help to diagnose the problem.

I cannot stress enough how a reproducible test case is the most useful contribution you can make in such cases... 

Thanks!

**Comment by maciej** [comment]
Hi,

After closer inspection and a reproduction attempt on a smaller dataset I found the cause of the bug. It was indeed a concurrency issue in my code. Building of the bitmap was singled before all input data was processed.

I'm sorry for bothering you and taking your time. At the same time thank you for the exhaustive description of a debugging procedure!

Let me close the issue.

**Comment by lemire** [comment]
@maciej  

Fantastic. We shall always be glad to help when needed. Please don't hesitate to report issues.
