### ISSUE TITLE
Question: Benchmark tests

### ISSUE THREAD

**Issue by Tornhoof** [lemire/RoaringBitmap#58]
Hello,
as I'm currently in the process of porting RoaringBitmaps to C#, I'm also porting those real data tests.
While my implementation has the same output cardinality as the unit tests, I can't really follow the time results of those tests.
For example:
````
  <testcase name="test[dataset=census-income, type=roaring, immutable=false]" classname="org.roaringbitmap.realdata.RealDataBenchmarkOrTest" time="1.469"/>
  <testcase name="test[dataset=census-income, type=roaring, immutable=true]" classname="org.roaringbitmap.realdata.RealDataBenchmarkOrTest" time="3.822"/>
````
The values appear to be too high, do they include the ZIP file part (loading and parsing the census data) or are there multiple iterations to the actual test. It uses JMH, which should handle all that warmup etc. stuff, but as I haven't done any Java work for over ten years I do not really know how e.g. the @Benchmark attribute works.

Are there any real performance benchmarks against the real data, which only handle the actual bitwise operations?

**Comment by lemire** [comment]
@Tornhoof 

Interesting project. Will you make it public?

I think that @gssiyankai  wrote our current real-data tests. Maybe he can comment.

I am not sure why you say that the numbers are "too high". What happens, say, when benchmarking the intersection (and) is that we take the 200 bitmaps (most datasets have 200 bitmaps, some have more) and we compute 199 successive intersections. So the number returned will be the sum of 199 intersections, say.

**Comment by Tornhoof** [comment]
Yes I will make it public as soon as I clean it up and find out how to use GIT with Visual Studio. I guess this weekend.
Apparently the testcase output snippet was cut from my previous comment.
For example:
Doing 200 consecutive Ors on the census-income dataset takes ~1.5s (or ~3.5 for the immutable version). In my current version the same benchmark (without the time for reading the zip) takes ~3ms.
This is a factor 1000 for the immutable version. If i take the zip reading into account my version also takes around 3s. That's why I'm confused what the real-data benchmark is actually doing.

**Comment by lemire** [comment]
@Tornhoof 

No, the benchmarks do not account for the time required to extract the data from the zip files. When the tests run, they run on pre-prepared data in memory.

Because we test not just one library, but several of them, and we compare the results, we have good confidence that Roaring is not particularly slow. In fact, as you may observe, it does quite well (which is the point of these tests). 

So you are saying that you are 500 times faster in C#. My first guess is that you are not measuring what you think you are measuring.

It is hard to tell in the abstract, but when you run your benchmark, do you check the output to make sure that the computations are done, and done correctly? A common problem with benchmarks is that the computations are optimized away or simply not done properly.

Possibly one could compare against an alternative like EWAH? https://github.com/lemire/csharpewah

**Comment by Tornhoof** [comment]
I solved it and it's a problem of PEBCAK.
I simply didn't pipe the jmh output into a file, so the only data I could find were those unit tests for the benchmarks and those were the wrong ones. Now after running the benchmark.jar manually and piping the output I actually see all that JMH output :)
So a valid comparison would be now:
Java: 3012,222 ±(99.9%) 16,152 us/op [Average]
C#: 3213,093 us

My version is currently immutable (as in defined by C# , which means private constructors, readonly fields etc.) and has no RLE encoding.

Sorry again for the confusion and thanks for the help.

**Comment by lemire** [comment]
@Tornhoof 

Keep us posted on the evolution of your project.

**Comment by Tornhoof** [comment]
@lemire 
As previously announced, I pushed my version to https://github.com/Tornhoof/RoaringBitmap
It includes the basic bitwise operators and enough unit tests to cover them, including your realdata tests.
Notably serialization is currently missing.
As for performance, my version is 10-20% slower than your current Java implementation using a microbenchmark system similar to JMH.

**Comment by lemire** [comment]
@Tornhoof 

Great stuff!
